In [1]:
import pandas as pd
import os

In [2]:
directory = r"C:\Users\HP\OneDrive\Desktop\summarizer"

# List of CSV files to merge
csv_files = [
    "Ltr20250724_122235.csv",
    "Ltr20250724_123704.csv",
    "later 220250724_121426.csv",  
    "ai_ml_articles_20250723_132012.csv",
    "arxiv_ai_abstracts.csv",
    "datascienceplus_articles.csv",
    "last20250725_122248.csv",
    "later20250724_120426.csv",
    "shyambhu_all_posts.csv"
]

# Initialize an empty list to store DataFrames
dataframes = []

# Load each CSV file
for file in csv_files:
    file_path = os.path.join(directory, file)
    if os.path.exists(file_path):  
        try:
            df = pd.read_csv(file_path)
            dataframes.append(df)
            print(f"Successfully loaded: {file}")
        except Exception as e:
            print(f"Error loading {file}: {e}")
    else:
        print(f"File not found: {file}")

# Merge all DataFrames
if dataframes:
    merged_data = pd.concat(dataframes, ignore_index=True)
    
    # Optional: Remove duplicates based on 'title' and 'url' if they exist
    if all(col in merged_data.columns for col in ['title', 'url']):
        merged_data = merged_data.drop_duplicates(subset=['title', 'url'], keep='first')
    
    # Save the merged DataFrame to a new CSV
    output_file = os.path.join(directory, "merged_data.csv")
    merged_data.to_csv(output_file, index=False, encoding='utf-8')
    print(f"Merged {len(merged_data)} articles and saved to {output_file}")
else:
    print("No files were loaded successfully.")

# Display the first few rows of the merged DataFrame 
if 'merged_data' in locals():
    print("\nPreview of merged data:")
    print(merged_data.head())

Successfully loaded: Ltr20250724_122235.csv
Successfully loaded: Ltr20250724_123704.csv
Successfully loaded: later 220250724_121426.csv
Successfully loaded: ai_ml_articles_20250723_132012.csv
Successfully loaded: arxiv_ai_abstracts.csv
Successfully loaded: datascienceplus_articles.csv
Successfully loaded: last20250725_122248.csv
Successfully loaded: later20250724_120426.csv
Successfully loaded: shyambhu_all_posts.csv
Merged 1518 articles and saved to C:\Users\HP\OneDrive\Desktop\summarizer\merged_data.csv

Preview of merged data:
                                               title  \
0  Bitcoin Price Analysis as a Tool for Blockchai...
1  Updates from the NeurIPS 2025 Position Paper T...
2  Tech giants split on EU AI code as compliance ...
3                                          Import AI
4          How to use AI to start an online business

                                                 url  word_count  \
0  https://thedatascientist.com/bitcoin-price-ana...      1126.0
1  https://blog.neurips.cc/2025/06/06/updates-fro...       727.0
2  https://www.artificialintelligence-news.com/ne...      1074.0
3  https://jack-clark.net/2025/06/23/import-ai-41...      2190.0
4  https://www.artificialintelligence-news.com/ne...      1015.0

                                             content Title Content  URL Date  \
0  The Data Scientist For blockchain decision-mak...   NaN     NaN  NaN  NaN
1  Communications Chairs 20252025 Conference Barb...   NaN     NaN  NaN  NaN
2  AI News is part of the TechForge Publications ...   NaN     NaN  NaN  NaN
3  Welcome to Import AI, a newsletter about AI re...   NaN     NaN  NaN  NaN
4  AI News is part of the TechForge Publications ...   NaN     NaN  NaN  NaN

   published_date text
0             NaN  NaN
1             NaN  NaN
2             NaN  NaN
3             NaN  NaN
4             NaN  NaN

In [3]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1518 entries, 0 to 4000
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           1517 non-null   object
 1   url             1517 non-null   object
 2   word_count      1364 non-null   float64
 3   content         1311 non-null   object
 4   Title           1 non-null      object
 5   Content         1 non-null      object
 6   URL             0 non-null      object
 7   Date            0 non-null      object
 8   published_date  0 non-null      float64
 9   text            153 non-null    object
dtypes: float64(2), object(8)
memory usage: 130.5+ KB

In [4]:
merged_data.describe(include='all')

,title,url,word_count,content,Title,Content,URL,Date,published_date,text
count,1517,1517,1364.000000,1311,1,1,0,0,0.0,153
unique,1343,1517,NaN,1311,1,1,0,0,NaN,153
top,Stats and R,https://thedatascientist.com/bitcoin-price-ana...,NaN,The Data Scientist For blockchain decision-mak...,ThinkAct: Vision-Language-Action Reasoning via...,Vision-language-action (VLA) reasoning tasks r...,NaN,NaN,NaN,Certainly! Here's a comprehensive blog post th...
freq,74,1,NaN,1,1,1,NaN,NaN,NaN,1
mean,NaN,NaN,1215.027859,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,1135.904557,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,559.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,936.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,1495.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,10519.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
cols_to_drop = ['Title', 'Content', 'URL', 'Date', 'published_date', 'text']
merged_data = merged_data.drop(columns=[col for col in cols_to_drop if col in merged_data.columns])

# Drop rows where content is missing
merged_data = merged_data.dropna(subset=['content'])

# Reset index
merged_data = merged_data.reset_index(drop=True)

print("Cleaned shape:", merged_data.shape)
merged_data.head()

Cleaned shape: (1311, 4)

,title,url,word_count,content
0,Bitcoin Price Analysis as a Tool for Blockchai...,https://thedatascientist.com/bitcoin-price-ana...,1000,The Data Scientist For blockchain decision-mak...
1,Updates from the NeurIPS 2025 Position Paper T...,https://blog.neurips.cc/2025/06/06/updates-fro...,727,Communications Chairs 20252025 Conference Barb...
2,Tech giants split on EU AI code as compliance ...,https://www.artificialintelligence-news.com/ne...,1000,AI News is part of the TechForge Publications ...
3,Import AI,https://jack-clark.net/2025/06/23/import-ai-41...,1000,"Welcome to Import AI, a newsletter about AI re..."
4,How to use AI to start an online business,https://www.artificialintelligence-news.com/ne...,1000,AI News is part of the TechForge Publications ...

In [17]:
merged_data.isnull().sum()

title         0
url           0
word_count    0
content       0
dtype: int64

In [18]:
merged_data['word_count'] = merged_data['content'].fillna('').apply(lambda x: len(str(x).split()))
merged_data = merged_data.dropna(subset=['title', 'url'])

In [19]:
merged_data.head()

,title,url,word_count,content
0,Bitcoin Price Analysis as a Tool for Blockchai...,https://thedatascientist.com/bitcoin-price-ana...,1000,The Data Scientist For blockchain decision-mak...
1,Updates from the NeurIPS 2025 Position Paper T...,https://blog.neurips.cc/2025/06/06/updates-fro...,727,Communications Chairs 20252025 Conference Barb...
2,Tech giants split on EU AI code as compliance ...,https://www.artificialintelligence-news.com/ne...,1000,AI News is part of the TechForge Publications ...
3,Import AI,https://jack-clark.net/2025/06/23/import-ai-41...,1000,"Welcome to Import AI, a newsletter about AI re..."
4,How to use AI to start an online business,https://www.artificialintelligence-news.com/ne...,1000,AI News is part of the TechForge Publications ...

In [1]:
from transformers import pipeline

# Load summarization pipeline with distilBART
summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")

# Example long text
text = """Machine learning is a subset of artificial intelligence that focuses on building systems that learn from and make decisions based on data. These systems improve over time without being explicitly programmed."""

# Get summary
summary = summarizer(text, max_length=50, min_length=10, do_sample=False)
print("Summary:", summary[0]['summary_text'])

model.safetensors:   1%|          | 10.5M/1.23G [00:00<?, ?B/s]

Device set to use cpu
Your max_length is set to 50, but your input_length is only 35. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=17)

Summary:  Machine learning is a subset of artificial intelligence that focuses on building systems that learn from and make decisions based on data . These systems improve over time without being explicitly programmed .